/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.tienda.sventasropa.UI;

/**
 *
 * @author marco
 */
public class JAddClientForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form JClientForm
     */
    public JAddClientForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelForm = new javax.swing.JPanel();
        labelId = new javax.swing.JLabel();
        fieldId = new javax.swing.JTextField();
        labelName = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        labelPhone = new javax.swing.JLabel();
        fieldPhone = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        scrollClients = new javax.swing.JScrollPane();
        tableClients = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Client Managment");
        setPreferredSize(new java.awt.Dimension(800, 500));

        panelForm.setBackground(new java.awt.Color(0, 204, 204));
        panelForm.setBorder(javax.swing.BorderFactory.createTitledBorder("Client Data"));
        panelForm.setLayout(new java.awt.GridLayout(5, 2, 8, 8));

        labelId.setText("ID:");
        panelForm.add(labelId);

        fieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIdActionPerformed(evt);
            }
        });
        panelForm.add(fieldId);

        labelName.setText("Name:");
        panelForm.add(labelName);

        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });
        panelForm.add(fieldName);

        labelEmail.setText("Email:");
        panelForm.add(labelEmail);
        panelForm.add(fieldEmail);

        labelPhone.setText("Phone:");
        labelPhone.setToolTipText("");
        panelForm.add(labelPhone);
        panelForm.add(fieldPhone);

        btnSave.setBackground(new java.awt.Color(102, 102, 255));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save Client");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        panelForm.add(btnSave);

        btnClear.setBackground(new java.awt.Color(255, 102, 102));
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        panelForm.add(btnClear);

        getContentPane().add(panelForm, java.awt.BorderLayout.PAGE_START);

        tableClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollClients.setViewportView(tableClients);

        getContentPane().add(scrollClients, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private com.tienda.sventasropa.service.ClientService clientService;

    public JAddClientForm(com.tienda.sventasropa.service.ClientService clientService) {
        this();
        this.clientService = clientService;
        initTable();
        loadClients();
    }

    private void initTable() {
        tableClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"ID", "Name", "Email", "Phone"}
        ) {
            public boolean isCellEditable(int row, int col) { return false; }
        });
    }

    private void loadClients() {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tableClients.getModel();
        model.setRowCount(0);
        if (clientService == null) return;
        for (com.tienda.sventasropa.model.Client c : clientService.getAllClients()) {
            model.addRow(new Object[]{
                c.getId(), c.getName(), c.getEmail(), c.getPhoneNumber()
            });
        }
    }

    private void saveClient() {
        try {
            int id       = Integer.parseInt(fieldId.getText().trim());
            String name  = fieldName.getText().trim();
            String email = fieldEmail.getText().trim();
            String phone = fieldPhone.getText().trim();
            clientService.registrarCliente(id, name, email, phone);
            loadClients();
            clearFields();
            javax.swing.JOptionPane.showMessageDialog(this, "Client saved successfully.");
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "ID must be a number.",
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(),
                "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }

    private void clearFields() {
        fieldId.setText("");
        fieldName.setText("");
        fieldEmail.setText("");
        fieldPhone.setText("");
    }
        
    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void fieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIdActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        saveClient();
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldId;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JPanel panelForm;
    private javax.swing.JScrollPane scrollClients;
    private javax.swing.JTable tableClients;
    // End of variables declaration//GEN-END:variables
}
