/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.tienda.sventasropa.UI;

/**
 *
 * @author marco
 */
public class JDeleteClientForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form JDeleteClientForm
     */
    public JDeleteClientForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        labelSearchId = new javax.swing.JLabel();
        fieldSearchId = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        scrollClients = new javax.swing.JScrollPane();
        tableClients = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Delete Clients");
        setPreferredSize(new java.awt.Dimension(650, 400));

        panelTop.setBackground(new java.awt.Color(255, 204, 204));
        panelTop.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete Client"));
        panelTop.setLayout(new java.awt.GridLayout(5, 8, 2, 8));

        labelSearchId.setText("Client ID:");
        panelTop.add(labelSearchId);
        panelTop.add(fieldSearchId);

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setText("Delete Client");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        panelTop.add(btnDelete);

        getContentPane().add(panelTop, java.awt.BorderLayout.PAGE_START);

        tableClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollClients.setViewportView(tableClients);

        getContentPane().add(scrollClients, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        deleteClient();
    }//GEN-LAST:event_btnDeleteActionPerformed
    private com.tienda.sventasropa.service.ClientService clientService;

    public JDeleteClientForm(com.tienda.sventasropa.service.ClientService clientService) {
        this();
        this.clientService = clientService;
        initTable();
        loadClients();
    }

    private void initTable() {
        tableClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"ID", "Name", "Email", "Phone"}
        ) {
            public boolean isCellEditable(int row, int col) { return false; }
        });

        tableClients.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && tableClients.getSelectedRow() != -1) {
                int row = tableClients.getSelectedRow();
                fieldSearchId.setText(tableClients.getValueAt(row, 0).toString());
            }
        });
    }

    private void loadClients() {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tableClients.getModel();
        model.setRowCount(0);
        if (clientService == null) return;
        for (com.tienda.sventasropa.model.Client c : clientService.getAllClients()) {
            model.addRow(new Object[]{
                c.getId(), c.getName(), c.getEmail(), c.getPhoneNumber()
            });
        }
    }

    private void deleteClient() {
        if (fieldSearchId.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Select a client from the table first.", "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete this client?",
            "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // TODO: conectar cuando Brigitte implemente deleteClient(id)
            javax.swing.JOptionPane.showMessageDialog(this,
                "Delete client coming soon.", "Info",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JTextField fieldSearchId;
    private javax.swing.JLabel labelSearchId;
    private javax.swing.JPanel panelTop;
    private javax.swing.JScrollPane scrollClients;
    private javax.swing.JTable tableClients;
    // End of variables declaration//GEN-END:variables
}
