/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.tienda.sventasropa.UI;

/**
 *
 * @author marco
 */
public class JEditClientForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form JEditClientForm
     */
    public JEditClientForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelId = new javax.swing.JLabel();
        fieldId = new javax.swing.JTextField();
        labelName = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        labelPhone = new javax.swing.JLabel();
        fieldPhone = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClients = new javax.swing.JTable();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Edit Client");
        setPreferredSize(new java.awt.Dimension(700, 480));
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit Client Data"));
        jPanel1.setLayout(new java.awt.GridLayout(5, 2, 8, 8));

        labelId.setText("ID:");
        jPanel1.add(labelId);

        fieldId.setEditable(false);
        fieldId.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(fieldId);

        labelName.setText("Name:");
        jPanel1.add(labelName);
        jPanel1.add(fieldName);

        labelEmail.setText("Email:");
        jPanel1.add(labelEmail);
        jPanel1.add(fieldEmail);

        labelPhone.setText("Phone:");
        jPanel1.add(labelPhone);
        jPanel1.add(fieldPhone);

        btnUpdate.setBackground(new java.awt.Color(153, 153, 255));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update Client");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);

        btnClear.setBackground(new java.awt.Color(255, 102, 102));
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tableClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableClients);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        updateClient();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed
    private com.tienda.sventasropa.service.ClientService clientService;

    public JEditClientForm(com.tienda.sventasropa.service.ClientService clientService) {
        this();
        this.clientService = clientService;
        initTable();
        loadClients();
    }

    private void initTable() {
        tableClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"ID", "Name", "Email", "Phone"}
        ) {
            public boolean isCellEditable(int row, int col) { return false; }
        });

        tableClients.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && tableClients.getSelectedRow() != -1) {
                int row = tableClients.getSelectedRow();
                fieldId.setText(tableClients.getValueAt(row, 0).toString());
                fieldName.setText(tableClients.getValueAt(row, 1).toString());
                fieldEmail.setText(tableClients.getValueAt(row, 2).toString());
                fieldPhone.setText(tableClients.getValueAt(row, 3).toString());
            }
        });
    }

    private void loadClients() {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tableClients.getModel();
        model.setRowCount(0);
        if (clientService == null) return;
        for (com.tienda.sventasropa.model.Client c : clientService.getAllClients()) {
            model.addRow(new Object[]{
                c.getId(), c.getName(), c.getEmail(), c.getPhoneNumber()
            });
        }
    }

    private void updateClient() {
        try {
            int id       = Integer.parseInt(fieldId.getText().trim());
            String name  = fieldName.getText().trim();
            String email = fieldEmail.getText().trim();
            String phone = fieldPhone.getText().trim();
            // TODO: conectar cuando Brigitte implemente editClient(id, name, email, phone)
            javax.swing.JOptionPane.showMessageDialog(this,
                "Edit client coming soon.", "Info",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Select a client from the table first.", "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void clearFields() {
        fieldId.setText("");
        fieldName.setText("");
        fieldEmail.setText("");
        fieldPhone.setText("");
        tableClients.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldId;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JTable tableClients;
    // End of variables declaration//GEN-END:variables
}
