/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.tienda.sventasropa.UI;

import com.tienda.sventasropa.repository.ClientRepository;
import com.tienda.sventasropa.repository.ProductRepository;
import com.tienda.sventasropa.repository.SaleRepository;
import com.tienda.sventasropa.service.ClientService;
import com.tienda.sventasropa.service.ProductService;
import com.tienda.sventasropa.service.SaleService;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author marco
 */
public class MainFrame extends javax.swing.JFrame {

    private final ClientService clientService;
    private final ProductService productService;
    private final SaleService saleService;

    /**
     * Creates new form MainFrameJava
     */
    public MainFrame() {
        // Inicializar repositorios
        ClientRepository clientRepository   = new ClientRepository();
        ProductRepository productRepository = new ProductRepository();
        SaleRepository saleRepository       = new SaleRepository();

        // Inicializar servicios
        clientService  = new ClientService(clientRepository);
        productService = new ProductService(productRepository);
        saleService    = new SaleService(saleRepository, productRepository);
        
        initComponents();
        
        // Personalización post-initComponents
        setTitle("Clothing Store - Management System");
        setSize(1100, 700);
        setLocationRelativeTo(null);
        desktopPane.setBackground(new Color(30, 30, 50));
        
        // Personalizar menú bar
        menuBar.setBackground(new Color(40, 40, 65));
        menuBar.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        clientsMenu = new javax.swing.JMenu();
        registerClientMenuItem = new javax.swing.JMenuItem();
        viewAllClientsMenuItem = new javax.swing.JMenuItem();
        productsMenu = new javax.swing.JMenu();
        addProductMenuItem = new javax.swing.JMenuItem();
        viewAllProductsMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        editProductMenuItem = new javax.swing.JMenuItem();
        deleteProductMenuItem = new javax.swing.JMenuItem();
        salesMenu = new javax.swing.JMenu();
        createSaleMenuItem = new javax.swing.JMenuItem();
        viewAllSalesMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clientsMenu.setText("Clients");

        registerClientMenuItem.setText("Register Client");
        clientsMenu.add(registerClientMenuItem);

        viewAllClientsMenuItem.setText("View All Clients");
        clientsMenu.add(viewAllClientsMenuItem);

        menuBar.add(clientsMenu);

        productsMenu.setText("Products");

        addProductMenuItem.setText("Add Product");
        addProductMenuItem.addActionListener(this::openProductForm);
        productsMenu.add(addProductMenuItem);

        viewAllProductsMenuItem.setText("View All Products");
        viewAllProductsMenuItem.addActionListener(this::openProductsTable);
        productsMenu.add(viewAllProductsMenuItem);
        productsMenu.add(jSeparator1);

        editProductMenuItem.setText("Edit Product");
        productsMenu.add(editProductMenuItem);

        deleteProductMenuItem.setText("Delete Product");
        productsMenu.add(deleteProductMenuItem);

        menuBar.add(productsMenu);

        salesMenu.setText("Sales");

        createSaleMenuItem.setText("Create Sale");
        salesMenu.add(createSaleMenuItem);

        viewAllSalesMenuItem.setText("View All Sales");
        salesMenu.add(viewAllSalesMenuItem);

        menuBar.add(salesMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed
    
    private void openProductForm() {
        JProductForm frame = new JProductForm(productService);
        desktopPane.add(frame);
        frame.setVisible(true);
    }
    
    private void openProductsTable() {
        JProductsTable frame = new JProductsTable(productService);
        desktopPane.add(frame);
        frame.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addProductMenuItem;
    private javax.swing.JMenu clientsMenu;
    private javax.swing.JMenuItem createSaleMenuItem;
    private javax.swing.JMenuItem deleteProductMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem editProductMenuItem;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu productsMenu;
    private javax.swing.JMenuItem registerClientMenuItem;
    private javax.swing.JMenu salesMenu;
    private javax.swing.JMenuItem viewAllClientsMenuItem;
    private javax.swing.JMenuItem viewAllProductsMenuItem;
    private javax.swing.JMenuItem viewAllSalesMenuItem;
    // End of variables declaration//GEN-END:variables

}
